version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: prometheus
    versions:
    - 0.11.0
- package-ecosystem: cargo
  directory: "/core/lib"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: prometheus
    versions:
    - 0.11.0
- package-ecosystem: cargo
  directory: "/core/codegen"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
