[package]
name = "instrumented-codegen"
version = "0.1.0"
authors = ["Brenden Matthews <brenden@diddyinc.com>"]
edition = "2018"

[dependencies]
darling = "0.9"
proc-macro2 = "1.0"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }

[lib]
proc-macro = true
